version: "3.9"
services:
  my-telegra-ph:
    build: ./
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./config.yml:/app/config.yml
      - ./logs:/app/logs
      - ./database:/app/database
      - ./media:/app/media
