version: "3.9"
services:
  my-telegra-ph:
    build: ./
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    expose:
      - "8000"  # Открывает порт внутри сети Docker (не пробрасывает наружу)
    volumes:
      - ./logs:/app/logs
      - ./database:/app/database
    networks:
      - my_network

  caddy:
    image: caddy:2.8.4
    restart: unless-stopped
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "80:80"  # HTTP порт
      - "443:443"  # HTTPS порт
    networks:
      - my_network

networks:
  my_network:
    driver: bridge