version: "3.9"
services:
  my-telegra-ph:
    build: ./
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    expose:
      - "8000"  # Открывает порт внутри сети Docker (не пробрасывает наружу)
    volumes:
      - ./logs:/app/logs
      - ./database:/app/database
    networks:
      - my_network
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/db  # Подключение к PostgreSQL

  caddy:
    image: caddy:2.8.4
    restart: unless-stopped
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "80:80"  # HTTP порт
      - "443:443"  # HTTPS порт
    networks:
      - my_network

  postgres:
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_USER: user        # Имя пользователя PostgreSQL
      POSTGRES_PASSWORD: password # Пароль пользователя
      POSTGRES_DB: db    # Имя базы данных
    volumes:
      - ./database/postgres_data:/var/lib/postgresql/data  # Тома для хранения данных PostgreSQL
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local