[tool.poetry]
name = "my-telegra-ph"
version = "0.1.0"
description = ""
authors = ["fedorov0av <fedorov0av@gmail.com>"]
readme = "README.md"
#packages = [{include = "my"}]

[tool.poetry.dependencies]
python = "^3.10"
loguru = "^0.7.3"
python-dotenv = "^1.0.1"
html-utils = {git = "https://github.com/fedorov0av/html-utils.git", rev = "v0.1.0"}
requests = "^2.32.3"
indexflow = {git = "https://github.com/fedorov0av/IndexFlow.git", rev = "v0.1.1"}
celery = "^5.4.0"
redis = "^5.2.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
